# Copyright 2023 Ecosoft Co., Ltd. (http://ecosoft.co.th)
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).

{
    "name" : "BOM Template For Continuous Line",
    "version" : "7.0.1.0.0",
    "author" : "Tharathip C.",
    "summary": "Create part based on BOM Template for continuous line",
    "category": "Warehouse",
    "sequence": 4,
    "website" : "http://www.ecosoft.co.th",
    "depends" : [
        "boi",
        "mrp_production_status",
        "product_bom_template",
    ],
    "data" : [
        # "data/bom.choice.skin.csv",
        # "data/bom.choice.thick.csv",
        # "data/bom.choice.width.csv",
        # "data/bom.choice.surface.csv",
        # "data/product.product.csv",
        # "data/mrp.bom.csv",
        # "data/00_slipjoint/mrp.bom.csv",
        # "data/01_secretjoint/mrp.bom.csv",
        # "data/02_roofjoint/mrp.bom.csv",
        # "data/03_board/mrp.bom.csv",
        # "data/mrp.machine.setup.master.csv",
        # "data/mrp.machine.setup.master.line.csv",
        "security/ir.model.access.csv",
        "wizards/product_make_bom_views.xml",
        "views/mrp_views.xml",
        "views/product_rapid_create_views.xml",
        "views/product_views.xml",
        "views/pallet_config_views.xml",
        "report/report_data.xml",
    ],
    "auto_install": False,
    "application": True,
    "installable": True,
}
